name: Build/Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  # --- 1. BUILD JOB ---
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Re-add ubuntu-latest if you need Linux builds
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      # - name: Build Linux
      #   if: matrix.os == 'ubuntu-latest'
      #   run: npm run build:linux

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.zip
            # dist/*.AppImage
            # dist/*.deb
            dist/*.yml
            dist/*.blockmap
          if-no-files-found: warn

  # --- 2. RELEASE JOB ---
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      # Compute release inputs in a shell step (industry standard).
      # We set outputs: tag_name, release_name, prerelease
      # - For a tag push (refs/tags/v1.2.3): tag_name = "v1.2.3", release_name = "v1.2.3", prerelease = false
      # - For a branch push (refs/heads/main): tag_name = "draft-main-<sha>", release_name = "Draft: main (<short-sha>)", prerelease = true
      - name: Set release variables
        id: vars
        run: |
          # detect tag vs branch
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            tag_name="${GITHUB_REF#refs/tags/}"
            release_name="$tag_name"
            prerelease="false"
          else
            branch_name="${GITHUB_REF#refs/heads/}"
            # sanitize branch name: replace slashes with dashes
            branch_name="${branch_name//\//-}"
            short_sha="${GITHUB_SHA:0:8}"    # use a short SHA (8 chars)
            tag_name="draft-${branch_name}-${short_sha}"
            release_name="Draft: ${branch_name} (${short_sha})"
            prerelease="true"
          fi

          # Export outputs for later steps
          echo "tag_name=${tag_name}" >> "$GITHUB_OUTPUT"
          echo "release_name=${release_name}" >> "$GITHUB_OUTPUT"
          echo "prerelease=${prerelease}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # --- This is the required logic ---
          
          # 1. For a tag push (e.g., v1.0.0), use the tag name: "v1.0.0"
          # 2. For a branch push, use the branch name + short SHA: "Draft: main (abc1234)"
          name: ${{ steps.vars.outputs.release_name }}
          
          # 1. For a tag push, use the tag name: "v1.0.0"
          # 2. For a branch push, create a unique tag: "draft-main-abc1234..."
          #    (This prefix avoids the 40-hex-char error)
          tag_name: ${{ steps.vars.outputs.tag_name }}
          
          # ---
          
          # Always create a draft as you wanted
          draft: false
          
          # Mark branch pushes (non-tags) as a pre-release
          prerelease: ${{ steps.vars.outputs.prerelease }}
          
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}